export const style = {
  page: "min-h-screen bg-background text-foreground",
  pageLanding: "min-h-screen bg-background text-foreground font-sans",

  container: "max-w-6xl mx-auto",
  containerSm: "max-w-3xl mx-auto",
  containerXs: "max-w-2xl mx-auto text-center",

  section: "py-20 px-6 border-t border-border",
  sectionBorderBottom: "border-b border-border",

  nav: "fixed top-0 left-0 right-0 z-50 border-b border-border bg-background/80 backdrop-blur-md",
  navInner: "max-w-6xl mx-auto px-6 h-16 flex items-center justify-between",
  navLinks: "hidden md:flex items-center gap-8 text-sm text-muted-foreground",
  navActions: "hidden md:flex items-center gap-3",
  navLink: "hover:text-foreground transition-colors",
  navLogoContainer: "flex items-center gap-2",
  navLogoText: "font-semibold text-foreground tracking-tight",

  header: "border-b border-border px-6 py-4",
  headerInner: "max-w-3xl mx-auto flex items-center justify-between",
  headerInfo: "flex items-center gap-3",

  flexCenter: "flex items-center gap-2",
  flexCenterGap3: "flex items-center gap-3",
  flexBetween: "flex items-center justify-between",
  flexStart: "flex items-start gap-3",
  flexCol: "flex flex-col items-center gap-1.5",
  flexColSmRow: "flex flex-col sm:flex-row gap-3",

  grid2: "grid md:grid-cols-2 gap-12 items-center",
  grid3: "grid md:grid-cols-3 gap-6",
  grid4: "grid sm:grid-cols-2 md:grid-cols-4 gap-4",
  gridCols3: "grid grid-cols-3 gap-3",
  gridCols6: "grid grid-cols-6 gap-1 border-t border-border pt-4",
  gridStats: "ml-auto grid grid-cols-2 gap-x-6 gap-y-1 text-right",

  card: "p-5 rounded-xl border border-border bg-card",
  cardHover: "p-5 rounded-xl border border-border bg-card hover:bg-secondary/30 transition-colors",
  cardSmall: "p-4 rounded-lg border border-border bg-card",
  cardBordered: "rounded-xl border border-border bg-card",
  cardBorderedRound: "rounded-2xl border border-border bg-card",
  cardRelative: "relative p-6 rounded-xl border border-border bg-card hover:border-primary/20 transition-colors group",
  cardAgent: "p-5 rounded-2xl border border-border bg-card space-y-3",
  cardResult: "p-5 rounded-xl border border-primary/20 bg-primary/5 cursor-pointer hover:bg-primary/10 transition-colors group",
  cardHistory: "w-full text-left p-4 rounded-lg border border-border bg-card hover:bg-secondary/30 hover:border-primary/20 transition-all group flex items-start justify-between gap-3",

  btnPrimary: "bg-primary text-primary-foreground",
  btnPrimarySm: "text-sm px-4 py-2 rounded-lg bg-primary text-primary-foreground font-medium hover:bg-primary/90 transition-all",
  btnPrimaryLg: "inline-flex items-center gap-2 px-8 py-3.5 rounded-lg bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-all group",
  btnPrimaryFull: "mt-2 w-full py-2.5 rounded-lg bg-primary text-primary-foreground text-sm font-medium",
  btnOutline: "text-sm px-4 py-2 rounded-lg border border-border text-muted-foreground hover:text-foreground hover:border-foreground/20 transition-all",
  btnOutlineLg: "flex items-center justify-center gap-2 px-6 py-3 rounded-lg border border-border text-muted-foreground hover:text-foreground hover:border-foreground/20 transition-all text-sm",
  btnAnalyze: "w-full py-4 rounded-xl font-semibold text-base transition-all flex items-center justify-center gap-3",
  btnAnalyzeActive: "bg-primary text-primary-foreground hover:bg-primary/90 active:scale-[0.99]",
  btnAnalyzeDisabled: "bg-secondary text-muted-foreground cursor-not-allowed",
  btnAction: "flex items-center justify-center gap-2 px-6 py-3 rounded-lg bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-all group",
  btnMobile: "md:hidden text-muted-foreground hover:text-foreground",
  btnBack: "text-muted-foreground mt-0.5 flex-shrink-0 group-hover:text-primary transition-colors",

  iconBox: "w-10 h-10 rounded-lg bg-secondary flex items-center justify-center mb-4",
  iconBoxSm: "w-8 h-8 rounded-md bg-secondary flex items-center justify-center flex-shrink-0",
  iconBoxLg: "w-9 h-9 rounded-lg bg-secondary flex items-center justify-center mb-3",
  iconBoxPrimary: "w-8 h-8 rounded-lg bg-primary/15 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconBoxYellow: "w-8 h-8 rounded-lg bg-yellow-400/15 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconBoxAccent: "w-8 h-8 rounded-lg bg-accent/15 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconBoxBlue: "w-8 h-8 rounded-lg bg-blue-500/15 flex items-center justify-center flex-shrink-0 mt-0.5",
  iconBoxPrimaryCircle: "w-14 h-14 rounded-2xl bg-primary/15 flex items-center justify-center mx-auto mb-6",
  iconBoxFooter: "w-5 h-5 rounded bg-primary/15 flex items-center justify-center",
  iconBoxNav: "w-7 h-7 rounded-md flex items-center justify-center",

  badge: "inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-primary/30 bg-primary/10 text-primary text-xs font-mono mb-6",

  title: "text-3xl font-bold text-foreground",
  titleSm: "text-3xl font-bold text-foreground mb-4",
  titleMd: "text-3xl font-bold text-foreground mb-5",
  titleHero: "text-4xl md:text-5xl font-bold text-foreground leading-[1.15] mb-5",
  titleSection: "text-center mb-14",
  subtitle: "font-semibold text-foreground mb-2",
  subtitleSm: "font-medium text-foreground text-sm mb-1",
  subtitleCard: "text-sm font-medium text-foreground",
  subtitleHeader: "text-sm font-semibold text-foreground",

  textMuted: "text-muted-foreground",
  textForeground: "text-foreground",
  textPrimary: "text-primary",
  textAccent: "text-accent",
  textBlue: "text-blue-400",
  textYellow: "text-yellow-400",
  textSm: "text-sm text-muted-foreground",
  textSmFg: "text-sm text-foreground",
  textXs: "text-xs text-muted-foreground",
  textXsLeading: "text-xs text-muted-foreground leading-relaxed",
  textXsMutedTop: "text-xs text-muted-foreground mt-0.5",
  textMonoXs: "text-xs font-mono text-muted-foreground",
  textMonoXsFlex: "text-xs font-mono text-muted-foreground flex items-center gap-1.5",
  textMonoLabel: "text-xs font-mono text-muted-foreground mb-1",
  textMonoTitle: "text-xs font-mono text-primary mb-3 uppercase tracking-widest",
  textMonoCard: "text-xs font-mono text-primary",
  textMonoFg: "text-xs font-mono text-foreground",
  textXlMono: "text-xl font-bold text-foreground font-mono",
  text4xlMono: "text-4xl font-bold text-foreground font-mono",
  textSectionLabel: "text-xs font-mono text-muted-foreground flex items-center gap-1.5",
  textSmMuted: "text-sm text-muted-foreground",
  textSmMutedLeading: "text-sm text-muted-foreground leading-relaxed",
  textSmLeading: "text-sm text-foreground leading-snug",
  textLgMuted: "text-muted-foreground text-lg leading-relaxed mb-8 max-w-md",
  textLgMutedCenter: "text-muted-foreground mb-8",
  textXsMutedCenter: "text-xs text-muted-foreground mt-0.5",
  textMutedIcon: "text-xs text-muted-foreground",
  textStep: "text-5xl font-black text-foreground/5 font-mono absolute top-4 right-5 select-none group-hover:text-foreground/8 transition-colors",
  textResultMuted: "text-xs font-mono text-muted-foreground mb-1",
  textResultFg: "text-sm text-foreground",
  textLocation: "text-[11px] text-muted-foreground font-mono flex items-center gap-1",
  textSpecs: "flex items-center gap-2 text-xs font-mono text-muted-foreground",

  chip: "px-1.5 py-0.5 rounded text-[10px] font-bold",
  forecastTime: "text-[10px] font-mono text-muted-foreground",
  statSub: "text-[10px] text-muted-foreground mt-0.5 font-mono",

  linkHover: "hover:text-foreground transition-colors",
  chevronIcon: "text-primary/50 group-hover:text-primary group-hover:translate-x-0.5 transition-all",
  agentCard: (color: string) => `flex gap-3 p-4 rounded-lg border ${color}`,
  analysisCard: "flex items-center gap-1.5 text-xs text-primary/70 group-hover:text-primary transition-colors",
  analysisHistoryHeader: "flex items-center gap-2 text-xs font-mono text-muted-foreground mb-3",
  analysisHeader: "flex items-center gap-2 text-xs font-mono text-muted-foreground border-b border-border pb-3 mb-1",
  resultHeader: "flex items-center gap-2 text-xs font-mono text-primary",
  resultChevron: "flex items-center gap-1.5 text-xs text-primary/70 group-hover:text-primary transition-colors",
  rowLabel: (color: string) => `font-mono px-1.5 py-0.5 rounded text-[10px] font-bold flex-shrink-0 ${color}`,

  mobileMenu: "md:hidden border-t border-border bg-background px-6 py-4 flex flex-col gap-4",
  heroSection: "pt-32 pb-24 px-6 max-w-6xl mx-auto",
  heroImage: "w-full h-64 object-cover opacity-70",
  heroGradient: "absolute inset-0 bg-gradient-to-t from-card via-card/50 to-transparent",
  heroBlur: "absolute -top-8 -right-8 w-48 h-48 bg-primary/10 rounded-full blur-3xl pointer-events-none",
  recommendationBox: "mt-4 pt-3 border-t border-border rounded-lg bg-secondary/50 p-3",
  statsRow: "mt-8 flex items-center gap-6",
  agentsHeader: "text-xs font-mono text-primary mb-3 uppercase tracking-widest",
  agentRow: "flex items-start gap-3 text-xs",
  weatherCard: "p-5 rounded-xl border border-border bg-card",
  weatherForecast: "grid grid-cols-6 gap-1 border-t border-border pt-4",

  footer: "border-t border-border py-8 px-6",
  footerInner: "max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-muted-foreground",
  footerBrand: "flex items-center gap-2",
  footerLinks: "flex gap-6",

  spaceY2: "space-y-2",
  spaceY4: "space-y-4",
  spaceY6: "space-y-6",

  pageFlex: "min-h-screen bg-background text-foreground flex flex-col",
  flexCenterFull: "flex-1 flex items-center justify-center px-6 py-12",
  containerLg: "w-full max-w-lg",

  headerFlexBetween: "border-b border-border px-6 py-4 flex items-center justify-between",
  headerSticky: "border-b border-border px-6 py-4 sticky top-0 bg-background/95 backdrop-blur z-10",
  headerInnerGap3: "max-w-3xl mx-auto flex items-center gap-3",
  headerMono: "text-xs text-muted-foreground font-mono",

  iconBoxTiny: "w-6 h-6 rounded bg-primary/15 flex items-center justify-center",
  iconBoxResultSm: "w-8 h-8 rounded-lg bg-secondary flex items-center justify-center",

  logoText: "text-sm font-semibold",
  divider: "h-4 w-px bg-border",

  progressBar: "flex gap-2 mb-10",
  progressStep: "h-1 flex-1 rounded-full transition-all duration-500",

  title2xl: "text-2xl font-bold text-foreground",
  textSmMutedTop: "text-muted-foreground mt-1 text-sm",
  textSmMutedSmall: "text-xs font-normal text-muted-foreground",
  textMutedFlex: "text-muted-foreground flex-shrink-0 mt-0.5",

  label: "text-sm font-medium text-foreground block mb-2",
  input: "w-full px-4 py-3 rounded-lg bg-secondary border border-border text-foreground placeholder-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary/50 focus:border-primary/50 transition-all",
  inputIcon: "w-full pl-10 pr-4 py-3 rounded-lg bg-secondary border border-border text-foreground placeholder-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary/50 focus:border-primary/50 transition-all",
  inputSuffix: "w-full px-4 py-3 rounded-lg bg-secondary border border-border text-foreground placeholder-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary/50 focus:border-primary/50 transition-all pr-16",
  inputIconPos: "absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground",
  inputSuffixText: "absolute right-4 top-1/2 -translate-y-1/2 text-xs font-mono text-muted-foreground",

  alertCard: "pt-2 p-4 rounded-lg bg-secondary/50 border border-border flex gap-2.5",

  gridCols3Sm: "grid grid-cols-3 gap-2",

  peakBtnBase: "flex flex-col items-center gap-1.5 p-3 rounded-lg border text-center transition-all",
  peakBtnActive: "border-primary bg-primary/10 text-primary",
  peakBtnInactive: "border-border bg-secondary text-muted-foreground hover:border-foreground/20 hover:text-foreground",
  textXsMedium: "text-xs font-medium",
  textMicroMono: "text-[10px] font-mono opacity-70",

  btnBackStep: "flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground disabled:opacity-30 disabled:cursor-not-allowed transition-colors",
  btnNext: "flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-semibold transition-all",
  btnBackResult: "flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors",

  cardPrimary: "p-5 rounded-xl border border-primary/25 bg-primary/8",
  cardAgentResult: (borderColor: string) => `p-5 rounded-xl border ${borderColor} bg-card`,

  textLgForeground: "text-foreground text-lg leading-relaxed",
  textSmMutedLeading5: "text-sm text-muted-foreground leading-relaxed",

  agentHeaderMuted: "text-xs font-mono text-muted-foreground py-2 flex items-center gap-2",

  flowBox: "p-5 rounded-xl border border-border bg-card",
  flowHeader: "text-xs font-mono text-muted-foreground mb-4 flex items-center gap-1.5",
  flowRow: "flex items-center justify-between",
  flowItem: "flex items-center gap-2",
  flowBadge: (color: string) => `${color} px-2.5 py-1 rounded text-[10px] font-mono font-bold text-background`,
  flowPlus: "text-muted-foreground text-xs",
  flowArrow: "text-muted-foreground text-xs mx-2",
  flowSynthesis: "bg-yellow-400/15 border border-yellow-400/30 px-2.5 py-1 rounded text-[10px] font-mono font-bold text-yellow-300",

  badgeAgent: (color: string) => `text-[10px] font-mono font-bold px-1.5 py-0.5 rounded border ${color}`,

  containerSmSpaceY5: "max-w-3xl mx-auto px-6 py-8 space-y-5",
};
